name: 111forecast

dependencies:
    - python=3.10.6
    - pip
    - pip:
        - discord.py==1.7.3
        - discord-ext-slash==0.9.2
        - discord-py-slash-command==1.1.0
        - requests==2.25.1
        - python-dotenv==0.21.0
        - Flask==2.3.2
        - waitress==2.1.2
